root: true
extends: chatur
rules:
  id-length: off
  class-methods-use-this:
    - error
    - exceptMethods:
      # These methods are often overridden to hide implementation
      # in parent class and throw error on invokation.
      - field
      - script
      - missing
      - format
      - gapPolicy
      - validationMethod
      - scoreMode
      - value
      - executionHint
      - _warn
  node/no-unsupported-features:
    - error
    # We use babel. So change the version
    # instead of inheriting from package.json#engines
    - version: 6
  # disabled because of too many false positives
  unicorn/no-fn-reference-in-iterator: off
  # doesn't work with eslint 5
  eslint-comments/no-unused-disable: off
