language: node_js

cache: yarn

node_js:
  - '8'
  - '7'
  - '6'
  - '4'

branches:
  except:
    - /^v\d+\.\d+\.\d+$/

before_install: yarn global add greenkeeper-lockfile@1

before_script: greenkeeper-lockfile-update

script: yarn run check

# Only the node version 8 job will upload the lockfile
after_script:
  - greenkeeper-lockfile-upload
  - yarn run coverage
